### ISSUE TITLE
Inscription via OAuth

### ISSUE THREAD

**Issue by AntoineDewaele** [DoEat/app.doeat#7]
Implémenter l'inscription / connexion via OAuth :

- [x]  Appel à la route `/sessions/create_auth` de l'api
- [ ] Envoi des informations : name, uid, token, first-name, last-name, email
- [ ] Récéption de l'id de l'utilisateur ainsi que de l'api token

**Comment by beauraF** [comment]
first-name, last-name ? C'est à moi de scinder l'attribut name initial ?

**Comment by beauraF** [comment]
La route `/sessions/create_auth` existe de ton coté ? Si oui, peux-tu la push sur Heroku ?

**Comment by beauraF** [comment]
miss click

**Comment by beauraF** [comment]
`{:provider=>"facebook", :uid=>"103269570163258", :token=>"TOKEN", :email=>"EMAIL@EMAIL.COM", :"first-name"=>"Jean", :"last-name"=>"Pierre"}`

`Completed 500 Internal Server Error`

**Comment by AntoineDewaele** [comment]
Ta requête est mal construite. Je t'invite à regarder http://docs.doeat.apiary.io/#reference/0/sessions/sign-in-with-oauth

En ce qui concerne la 500, l'api devrait renvoyer correctement l'erreur désormais ;)

**Comment by beauraF** [comment]
J'vais enquêter un peu plus. Je te tiens au jus.
